### ISSUE TITLE
Oops - context menus again

### ISSUE THREAD

**Issue by ghost** [wbond/sublime_tortoise#2]
Accidentally closed that issue on menus...

Looked at the console, no errors when I right-click, and no menus

**Comment by ghost** [comment]
OK - investigated a bit more and am seeing these errors (repeated 8 or so times) in the console when I right click on the text of a file under SVN control (windows XP)

<pre><code>Traceback (most recent call last):
  File ".\sublime_plugin.py", line 201, in is_visible_
  File ".\Tortoise.py", line 57, in handler
  File ".\Tortoise.py", line 252, in is_visible
  File ".\Tortoise.py", line 431, in get_status
KeyError: 'status'</code></pre>

**Comment by wbond** [comment]
This is fixed in the latest version, thanks for reporting it!
