### ISSUE TITLE
Problem with TortoiseGit 1.8.0.0

### ISSUE THREAD

**Issue by wasilak** [wbond/sublime_tortoise#20]
I have updated today my TortoiseGit and when I tried to commit through Sublime Text 2 it 
stopped working, here is error:

![2013-01-29 16_18_42](https://f.cloud.github.com/assets/436730/107366/204bee02-6a28-11e2-9fc9-94404f49bfe8.png)

Seems like in new TortoiseGit TortoiseProc.exe is missing...

Besides that - great work :)

Peter

**Comment by orand** [comment]
It appears TortoiseProc.exe was renamed to TortoiseGitProc.exe in 1.8.0.  When I update my Tortoise.sublime-settings file with this new filename, I get the following error when I right-click on a file or folder: "[Error 2] The system cannot find the file specified".  This might just be something wrong on my machine, so you might want to see if it works on your machine.

**Comment by wasilak** [comment]
I have changed filename in settings and now it works like a charm :)

Thanks for help :) :+1:

**Comment by fyneworks** [comment]
We've been having some trouble using Tortoise with ST3 so we threw together a simple plugin to help commit/push stuff. and it has a shortcut to git bash.
https://github.com/fyneworks/sublime-TortoiseGIT
