### ISSUE TITLE
Context menus in folder tray - delays

### ISSUE THREAD

**Issue by ghost** [wbond/sublime_tortoise#3]
Thanks for fixing the context menu issue I reported before. It seems there is a new problem. If you right click on a folder with a lot of subfolders and files in it, it takes a good few minutes before the context menu appears - leaving the editor locked in the mean time

**Comment by wbond** [comment]
So unfortunately the svn command line program for windows sometimes runs a little slow. I have a really fast computer, so I created a 2-second cache TTL for the status commands so they don't have to be queried multiple times. My guess is that your machine wasn't completing within that two seconds, so it was checking the status multiple times per right-click.

I've updated the plugin to have a 10 second TTL, so hopefully you should get much better performance. If this doesn't work, it looks like I would probably have to come up with a different algorithm for fetching and caching SVN statuses.

**Comment by ghost** [comment]
Unfortunately this seems to have made no difference at all

**Comment by wbond** [comment]
Unfortunately this isn't something I have the time to debug and fix. If it would help, I could add an option to disable the context menus.

**Comment by wbond** [comment]
I did some work on this recently and fixed various bugs. I fixed some issues with file paths containing spaces and also with status caching. Hopefully this will solve your problems.

If you still have trouble, you can enable debug messages by editing the settings via the Preferences > Package Settings > Tortoise menu. These will appear in the console. There is also a setting to disable menu entries for better performance.

Also, if you want to check out my new plugin Package Control, it allows for easy and automatic upgrades of this plugin, along with a whole host of other stuff. You can check it out at http://wbond.net/sublime_packages/package_control.

**Comment by ghost** [comment]
Thanks for this, unfortunately on the latest version, the context menus from the project side-bar are now taking longer than ever to appear, and when they do appear, an error immediately appears so the menu is unusable:

error: global name 'root_dir' is not defined
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
    return self.is_visible(**args)
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 208, in is_visible
  File ".\Tortoise.py", line 400, in get_status
  File ".\Tortoise.py", line 373, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: global name 'root_dir' is not defined
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
    return self.is_visible(**args)
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 244, in is_visible
  File ".\Tortoise.py", line 400, in get_status
  File ".\Tortoise.py", line 373, in process_status
UnboundLocalError: local variable 'status' referenced before assignment
error: global name 'root_dir' is not defined
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 197, in is_visible_
    return self.is_visible(**args)
  File ".\Tortoise.py", line 75, in handler
  File ".\Tortoise.py", line 222, in is_visible
  File ".\Tortoise.py", line 400, in get_status
  File ".\Tortoise.py", line 373, in process_status
UnboundLocalError: local variable 'status' referenced before assignment

Going to try with the menus disabled now, see how the functionality is

**Comment by wbond** [comment]
Wow, I'm really having trouble getting this to work for you. :-)

There is a new version which should have fixed the status and root_dir errors. Let me know if it works!

**Comment by ghost** [comment]
OK - no more errors and all seems to be working as advertised. Menus are still slow to come up, but the caching works. I think the slowness is due to Tortoise running slowly - especially over a network. Thanks for your work on this

**Comment by wbond** [comment]
I’m glad it is all working now. Accessing SVN over a network will definitely be really slow. It may be worth your while to disable the menu entries just for the sake of being able able to use other commands in the context menu. Either way, I’ll leave that to you!
