### ISSUE TITLE
No module named thginithook

### ISSUE THREAD

**Issue by williamledoux** [wbond/sublime_tortoise#4]
When I right-click on a folder and select Tortoise Diff, I get the following error message:

```
{{{
#!python
** Mercurial version (1.9.1).  TortoiseHg version (2.1.2)
** Command: vdiff @Include
** CWD: Q:\@Documents
** Encoding: cp1252
** Extensions loaded: mq, extdiff, rebase, transplant
** Python version: 2.6.6 (r266:84297, Aug 24 2010, 18:13:38) [MSC v.1500 64 bit (AMD64)]
** Windows version: (6, 1, 7601, 2, 'Service Pack 1')
** Processor architecture: x64
** Qt-4.7.1 PyQt-4.8.3
Traceback (most recent call last):
  File "tortoisehg\hgqt\run.pyo", line 504, in __call__
  File "mercurial\demandimport.pyo", line 85, in _demandimport
ImportError: No module named thginithook

}}}
```

Though, if I type the following command in a shell, everything is fine:

```
C:\progs64\TortoiseHg\thg.exe vdiff Q:\@Documents\@Include
```

**Comment by wbond** [comment]
This appears to be a bug in TortoiseHg, and it appears it is fixed in the latest nightly release https://bitbucket.org/tortoisehg/thg/issue/1042/crashed-when-opening-visual-diff-on-a-file.

**Comment by wbond** [comment]
Please feel free to reopen this issue if using the latest nightly of TortoiseHg does not help.

**Comment by williamledoux** [comment]
Thanks, it fixed the problem.
For potential readers, the nightly builds can be found here: https://bitbucket.org/tortoisehg/thg-winbuild/downloads
