### ISSUE TITLE
Context menu in case of nested HG repositories

### ISSUE THREAD

**Issue by williamledoux** [wbond/sublime_tortoise#5]
Hi there,

I have a layout with one HG repository (A) containing a couple of HG repositories (B and C)
The folder A is added to a sublime project.
All commands that I execute by right clicking on one of the subfolders (B and C) are executed on A.

Thanks for your amazing work !

**Comment by wbond** [comment]
Ok, I think I have an idea of what is going on.

Are you using the mercurial subrepos functionality for this?

**Comment by williamledoux** [comment]
No the setup is as simple as I explained. (There is no hgsub file)

**Comment by wbond** [comment]
Ok, thanks for the feedback. I'm not very familiar with nesting, which is why I asked about the subrepos, but know that I know exactly how you are doing it I should be able to replicate it and get the bug fixed.

**Comment by wbond** [comment]
This should be fixed in version 1.1.4 (17b390d7).

**Comment by williamledoux** [comment]
Works perfectly, Thanks !
