### ISSUE TITLE
Unavailable in package manager

### ISSUE THREAD

**Issue by edubkendo** [wbond/sublime_tortoise#9]
I have looked thoroughly, but I am completely unable to find this plugin in the package manager. As I believe you are also the author of said manager, I hesitated to install it manually out of concern that you might have deliberately disabled it. Thanks for making some wonderful and useful plugins, and running the site which makes it very easy to find and download the packages that make my workflow go so much more smoothly.

**Comment by wbond** [comment]
Are you running Windows, or another platform? The Tortoise plugin is only available for Windows and will not show up for OS X or Linux machines.

**Comment by edubkendo** [comment]
That explains it. Just recently switched from Windows to Ubuntu. Sorry, will close issue.
